### ISSUE TITLE
Error when creating a contract

### ISSUE THREAD

**Issue by Dominique-Roelants** [rudolfdeschipper/uProMIS4#12]
Error when creating a contract, for which a task was supposed to be created. After removing the task configuration, the error is still there

[4 - contract creation.log](https://github.com/rudolfdeschipper/uProMIS4/files/11464484/4.-.contract.creation.log)
![4 - error](https://github.com/rudolfdeschipper/uProMIS4/assets/133370947/d42ddfb5-cd13-4474-acb9-62286428fbab)

**Comment by rudolfdeschipper** [comment]
Fixed, user name in history was not filled, which gave an error upon save
